# Generated by Django 4.2.1 on 2023-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routes', models.TextField(max_length=80)),
                ('durations', models.TextField(max_length=40)),
                ('distances', models.TextField(max_length=50)),
                ('prices', models.TextField(max_length=60)),
            ],
        ),
    ]
