# Generated by Django 4.2.1 on 2023-06-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBus', '0002_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField(max_length=80)),
                ('floor', models.TextField(max_length=40)),
                ('duration', models.TextField(max_length=50)),
                ('prices', models.TextField(max_length=60)),
            ],
        ),
    ]
