# Generated by Django 4.2.1 on 2023-06-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBus', '0003_sleep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='prices',
        ),
    ]
