# Generated by Django 4.2.1 on 2023-06-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBus', '0004_remove_sleep_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='room',
            new_name='roomnumber',
        ),
    ]
